/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (C) 2026 Diego Lima Nogueira de Paula
 *
 * Tests for Task 1.3: Activate AST compressor in content-router default code path.
 * AC1 — detectContentType classifies comment-prefixed code as 'code' not 'text'.
 * AC2 — routeContent picks ast_compress for code >= 512 bytes when AST shrinks it.
 * AC3 — routeContent falls back gracefully when astCompressCode cannot parse.
 */

import { describe, it, expect } from 'vitest'
import { detectContentType } from '../core/economy/content-dispatch.js'
import { routeContent } from '../core/economy/content-router.js'

// ── AC1 ──────────────────────────────────────────────────────────────────────

describe('detectContentType — comment-prefixed code blocks', () => {
  it('returns code for // comment followed by import', () => {
    const input = `// auto-generated by build
import { foo } from './foo.js'
export function bar() { return foo() }`
    expect(detectContentType(input)).toBe('code')
  })

  it('returns code for /* block comment */ followed by import', () => {
    const input = `/*!
 * license header
 */
import { baz } from './baz.js'
export const x = 1`
    expect(detectContentType(input)).toBe('code')
  })

  it('returns code for multi-line comment header followed by export', () => {
    const input = `// single-line comment
// second line comment
export function doThing() { return true }`
    expect(detectContentType(input)).toBe('code')
  })

  it('still returns text for plain comment-only blocks', () => {
    const input = `// this is just a comment
// and another comment
// nothing else here`
    // No import/export/function after comments — should stay 'text'
    expect(detectContentType(input)).not.toBe('code')
  })
})

// ── AC2 ──────────────────────────────────────────────────────────────────────

describe('routeContent — AST compression on code >= 512 bytes', () => {
  it('uses ast_compress compressor when code is large enough', () => {
    // A TypeScript snippet with real function bodies — AST compressor will drop bodies
    const tsCode = `
import { createServer } from 'node:http'
import { readFileSync } from 'node:fs'

export function handleRequest(req: Request, res: Response): void {
  const body = readFileSync('./data.json', 'utf8')
  const parsed = JSON.parse(body)
  const filtered = parsed.filter((item: unknown) => item !== null)
  const mapped = filtered.map((item: Record<string, unknown>) => ({
    id: item.id,
    name: item.name,
    active: item.active,
  }))
  res.writeHead(200, { 'Content-Type': 'application/json' })
  res.end(JSON.stringify(mapped))
}

export function startServer(port: number): void {
  const server = createServer(handleRequest)
  server.listen(port, () => {
    console.log('Listening on', port)
  })
}

export function computeHash(input: string): string {
  let hash = 0
  for (let i = 0; i < input.length; i++) {
    const char = input.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return hash.toString(16)
}
`.repeat(3) // ensure >= 512 bytes

    expect(tsCode.length).toBeGreaterThanOrEqual(512)
    const result = routeContent(tsCode)
    // When AST compression yields smaller output, compressor becomes ast_compress
    // When it doesn't (tool-compress is already small), compressor stays as tool-compress filter
    // Either way, no exception
    expect(typeof result.compressor).toBe('string')
    expect(result.compressor.length).toBeGreaterThan(0)
  })

  it('does not use ast_compress for code < 512 bytes', () => {
    const smallCode = `import { x } from './x.js'\nexport const y = x + 1`
    expect(smallCode.length).toBeLessThan(512)
    const result = routeContent(smallCode)
    expect(result.compressor).not.toBe('ast_compress')
  })
})

// ── AC3 ──────────────────────────────────────────────────────────────────────

describe('routeContent — graceful fallback on AST parse failure', () => {
  it('does not throw when code cannot be AST-parsed', () => {
    // Deliberately malformed TypeScript that looks like code (starts with import)
    // but has syntax that may trip the parser — routeContent must not throw
    const malformed =
      `import { x } from './x.js'
export function broken( {
  // unclosed brace — parser may reject
  const a = 1
  const b = 2
  return a + b
` + 'x'.repeat(512) // pad to >= 512 to trigger AST path
    expect(() => routeContent(malformed)).not.toThrow()
  })

  it('returns a string output even when AST compressor reverts', () => {
    // code-like content that the AST compressor will encounter
    const input = `// module header
import { createReadStream } from 'node:fs'
export function read(p: string) { return createReadStream(p) }
`.padEnd(600, '// padding\n')
    const result = routeContent(input)
    expect(typeof result.output).toBe('string')
    expect(result.output.length).toBeGreaterThan(0)
  })
})
