/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 */

/**
 * Contract Scaffolder — generates HTTP/MCP handler skeletons from `contract` nodes.
 *
 * Pure function: no file I/O. Returns descriptors for the caller to persist.
 *
 * For each contract:
 *   - Imports input/output schemas from src/schemas/
 *   - Calls .parse() on both sides (validation guard before core)
 *   - Returns 400/ValidationError on parse failure without reaching core
 *   - Falls back to z.unknown() + TODO when output schema is absent
 */

export type HandlerType = 'rest' | 'mcp'

export interface ContractSpec {
  readonly id: string
  readonly name: string
  readonly description?: string
  readonly inputSchemaRef: string
  readonly outputSchemaRef: string | null
  readonly handlerType: HandlerType
  /**
   * Reference to the core function to call (e.g. 'createUser').
   * When provided, the scaffolder emits an import + call instead of a TODO placeholder.
   * Also triggers generation of a test file skeleton for the core fn.
   */
  readonly coreFnRef?: string
}

export interface ContractScaffoldOptions {
  readonly handlerDir?: string
}

export interface ScaffoldedFile {
  readonly path: string
  readonly content: string
}

export interface ContractScaffoldResult {
  readonly handlerFile: ScaffoldedFile
  /** Generated test skeleton when coreFnRef is supplied; undefined otherwise. */
  readonly testFile?: ScaffoldedFile
  readonly warnings: string[]
}

// ── Public API ─────────────────────────────────────────────────────────────

/** scaffoldContract —  */
export function scaffoldContract(spec: ContractSpec, options: ContractScaffoldOptions = {}): ContractScaffoldResult {
  const handlerDir = options.handlerDir ?? 'src/core/generated/handlers/'
  const slug = toKebab(spec.name)
  const warnings: string[] = []

  const outputSchemaRef = spec.outputSchemaRef ?? 'z.unknown()'
  if (!spec.outputSchemaRef) {
    warnings.push(
      `Contract "${spec.name}" has no output schema — using z.unknown(). ` +
        `Add outputSchemaRef to enforce output validation.`,
    )
  }

  const content =
    spec.handlerType === 'rest' ? generateRestHandler(spec, outputSchemaRef) : generateMcpHandler(spec, outputSchemaRef)

  const testFile: ScaffoldedFile | undefined = spec.coreFnRef
    ? {
        path: `src/tests/${slug}-handler.test.ts`,
        content: generateTestSkeleton(spec, spec.coreFnRef),
      }
    : undefined

  return {
    handlerFile: { path: `${handlerDir}${slug}-handler.ts`, content },
    testFile,
    warnings,
  }
}

// ── REST handler generator ─────────────────────────────────────────────────

function generateRestHandler(spec: ContractSpec, outputSchemaRef: string): string {
  const hasOutputSchema = spec.outputSchemaRef !== null
  const outputImport = hasOutputSchema ? `, ${outputSchemaRef}` : ''
  const outputSchemaExpr = hasOutputSchema
    ? outputSchemaRef
    : `z.unknown() /* TODO: define output schema for ${spec.name} */`

  return `// AUTO-GENERATED by contract-scaffolder — do not edit manually
// Contract: ${spec.name} (${spec.id})
// ${spec.description ?? ''}
// Schemas: src/schemas/${toKebab(spec.inputSchemaRef.replace(/Schema$/, ''))}.schema.ts

import type { Request, Response } from "express";
import { z } from "zod/v4";
import { ${spec.inputSchemaRef}${outputImport} } from "../../schemas/${toKebab(spec.inputSchemaRef.replace(/Schema$/, ''))}.schema.js";
import { ValidationError } from "../../core/utils/errors.js";

const OutputSchema = ${outputSchemaExpr};
type Output = z.infer<typeof OutputSchema>;

/** handle$ —  */
export async function handle${spec.name}(req: Request, res: Response): Promise<void> {
  // ── Input validation ─────────────────────────────────────────────
  let validatedInput: z.infer<typeof ${spec.inputSchemaRef}>;
  try {
    validatedInput = ${spec.inputSchemaRef}.parse(req.body);
  } catch (err) {
    res.status(400).json({
      error: "ValidationError",
      message: err instanceof Error ? err.message : "Invalid input",
    });
    return;
  }

  // CORE: implement business logic below (validated input guaranteed)
  const coreResult: Output = OutputSchema.parse(
    ${spec.coreFnRef ? `await ${spec.coreFnRef}(validatedInput)` : '{} /* TODO: call core function with validatedInput */'},
  );

  res.json(coreResult);
}
`
}

// ── MCP handler generator ──────────────────────────────────────────────────

function generateMcpHandler(spec: ContractSpec, outputSchemaRef: string): string {
  const hasOutputSchema = spec.outputSchemaRef !== null
  const outputImport = hasOutputSchema ? `, ${outputSchemaRef}` : ''
  const outputSchemaExpr = hasOutputSchema
    ? outputSchemaRef
    : `z.unknown() /* TODO: define output schema for ${spec.name} */`

  return `// AUTO-GENERATED by contract-scaffolder — do not edit manually
// MCP Tool Contract: ${spec.name} (${spec.id})
// ${spec.description ?? ''}
// Schemas: src/schemas/${toKebab(spec.inputSchemaRef.replace(/Schema$/, ''))}.schema.ts

import { z } from "zod/v4";
import { ${spec.inputSchemaRef}${outputImport} } from "../../schemas/${toKebab(spec.inputSchemaRef.replace(/Schema$/, ''))}.schema.js";
import { ValidationError } from "../../core/utils/errors.js";

const OutputSchema = ${outputSchemaExpr};
type Output = z.infer<typeof OutputSchema>;

/** execute$ —  */
export async function execute${spec.name}(rawInput: unknown): Promise<Output> {
  // ── Input validation ─────────────────────────────────────────────
  let validatedInput: z.infer<typeof ${spec.inputSchemaRef}>;
  try {
    validatedInput = ${spec.inputSchemaRef}.parse(rawInput);
  } catch (err) {
    throw new ValidationError(
      err instanceof Error ? err.message : "Invalid input",
      err instanceof z.ZodError ? err.issues : [],
    );
  }

  // CORE: implement business logic below (validated input guaranteed)
  const result: Output = OutputSchema.parse(
    ${spec.coreFnRef ? `await ${spec.coreFnRef}(validatedInput)` : '{} /* TODO: call core function with validatedInput */'},
  );

  return result;
}
`
}

// ── Test skeleton generator ────────────────────────────────────────────────

function generateTestSkeleton(spec: ContractSpec, coreFnRef: string): string {
  return `// AUTO-GENERATED test skeleton — fill in fixtures and assertions
// Contract: ${spec.name} (${spec.id})
import { describe, it, expect, vi } from 'vitest'

vi.mock('../../core/...', () => ({
  ${coreFnRef}: vi.fn(),
}))

describe('${spec.name} handler', () => {
  it('calls ${coreFnRef} with validated input', async () => {
    // TODO: set up mock, call handler, assert ${coreFnRef} was called
    expect(true).toBe(true)
  })
})
`
}

// ── Utilities ──────────────────────────────────────────────────────────────

function toKebab(name: string): string {
  return name.replace(/([A-Z])/g, (_, c: string) => `-${c.toLowerCase()}`).replace(/^-/, '')
}
