/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * §EPIC-agent-explode-view Task 1.4 — domain-skills + failure_signals aggregation
 * for the /api/agent/learnings endpoint.
 *
 * Pure deterministic aggregation — no LLM. Domain skills loaded from filesystem;
 * failure signals queried from SQLite grouped by signalKind.
 */

import type Database from 'better-sqlite3'
import { loadDomainSkills } from '../skills/domain-skill-loader.js'
import { createLogger } from '../utils/logger.js'

const log = createLogger({ layer: 'core', source: 'agent-learnings.ts' })

const LEARNINGS_LIMIT = 20
const FAILURE_WINDOW_DAYS = 7

export interface DomainSkillEntry {
  domain: string
  topic: string
  confidence: number
  summary: string
}

export interface FailureSignalEntry {
  signalKind: string
  count: number
  lastSeen: string
  severity: string
}

export interface PolicyObservationEntry {
  appliedRule: string
  timestamp: string
  divergence: boolean
}

export interface IssuePatternEntry {
  patternType: string
  count: number
  lastSeen: string
  suggestedRule: string | null
  autoGenerated: boolean
}

export interface AgentLearningsResult {
  domainSkills: DomainSkillEntry[]
  failures: FailureSignalEntry[]
  policies: PolicyObservationEntry[]
  rules: IssuePatternEntry[]
  learnings: string[]
  total: number
}

function extractHostname(context: string): string {
  try {
    return new URL(context).hostname.toLowerCase()
  } catch {
    return context.trim().toLowerCase()
  }
}

/** Returns true when the skill's domain matches the given hostname.
 *  Handles exact match and parent-domain: app.acme.com matches acme.com. */
function matchesDomain(skillDomain: string, hostname: string): boolean {
  const sd = skillDomain.toLowerCase()
  const hn = hostname.toLowerCase()
  return sd === hn || hn.endsWith('.' + sd)
}

function queryIssuePatterns(db: Database.Database): IssuePatternEntry[] {
  interface Row {
    pattern_type: string
    count: number
    last_seen: string
    suggested_rule: string | null
    auto_generated: number
  }
  let rows: Row[]
  try {
    rows = db
      .prepare<[], Row>(
        `SELECT pattern_type, count, last_seen, suggested_rule, auto_generated
         FROM issue_patterns
        ORDER BY count DESC`,
      )
      .all() as Row[]
  } catch {
    rows = []
  }
  return rows.map((r) => ({
    patternType: r.pattern_type,
    count: r.count,
    lastSeen: r.last_seen,
    suggestedRule: r.suggested_rule,
    autoGenerated: r.auto_generated === 1,
  }))
}

function queryRecentPolicyObservations(db: Database.Database): PolicyObservationEntry[] {
  const since = new Date(Date.now() - FAILURE_WINDOW_DAYS * 24 * 60 * 60_000).toISOString()
  interface Row {
    timestamp: string
    decision: string
    divergence: number
  }
  let rows: Row[]
  try {
    rows = db
      .prepare<[string], Row>(
        `SELECT timestamp, decision, divergence
         FROM policy_observations
        WHERE timestamp >= ?
        ORDER BY timestamp DESC
        LIMIT 10`,
      )
      .all(since) as Row[]
  } catch {
    rows = []
  }
  return rows.map((r) => {
    let appliedRule = 'unknown'
    try {
      const parsed = JSON.parse(r.decision) as { appliedRule?: string }
      appliedRule = parsed.appliedRule ?? 'unknown'
    } catch (err) {
      log.debug('agent-learnings: malformed decision JSON — using default', { err })
    }
    return { appliedRule, timestamp: r.timestamp, divergence: r.divergence === 1 }
  })
}

function queryActiveFailureSignals(db: Database.Database): FailureSignalEntry[] {
  const since = new Date(Date.now() - FAILURE_WINDOW_DAYS * 24 * 60 * 60_000).toISOString()
  interface Row {
    signalKind: string
    count: number
    lastSeen: string
    severity: string
  }
  let rows: Row[]
  try {
    rows = db
      .prepare<[string], Row>(
        `SELECT signalKind,
              COUNT(*) AS count,
              MAX(timestamp) AS lastSeen,
              MAX(severity) AS severity
         FROM failure_signals
        WHERE timestamp >= ?
        GROUP BY signalKind
        ORDER BY count DESC`,
      )
      .all(since) as Row[]
  } catch {
    rows = []
  }
  return rows.map((r) => ({
    signalKind: r.signalKind,
    count: r.count,
    lastSeen: r.lastSeen,
    severity: r.severity,
  }))
}

export function aggregateAgentLearnings(
  db: Database.Database,
  skillsDir: string,
  context?: string,
): AgentLearningsResult {
  const hostname = context ? extractHostname(context) : null
  const { skills } = loadDomainSkills(skillsDir)

  const matched: typeof skills = []
  const others: typeof skills = []

  for (const skill of skills) {
    if (hostname && matchesDomain(skill.domain, hostname)) {
      matched.push(skill)
    } else {
      others.push(skill)
    }
  }

  matched.sort((a, b) => b.confidence - a.confidence)
  others.sort((a, b) => b.confidence - a.confidence)

  const orderedSkills = [...matched, ...others]
  const failures = queryActiveFailureSignals(db)
  const policies = queryRecentPolicyObservations(db)
  const rules = queryIssuePatterns(db)

  // Build flat learnings list — domain skills first, then failures, policies, issue patterns; cap at 20
  const allLearnings: string[] = [
    ...orderedSkills.map((skill) => {
      const summary = skill.body.trim().split('\n')[0] ?? ''
      const suffix = summary ? ': ' + summary.slice(0, 100) : ''
      return `[domain-skill] ${skill.domain}/${skill.topic}${suffix}`
    }),
    ...failures.map((f) => `[failure-signal] ${f.signalKind} (×${f.count}, last: ${f.lastSeen})`),
    ...policies.map((p) => `[policy-observation] ${p.appliedRule} (${p.timestamp.slice(0, 10)})`),
    ...rules.map(
      (r) =>
        `[issue-pattern] ${r.patternType} (×${r.count}${r.suggestedRule ? ': ' + r.suggestedRule.slice(0, 80) : ''})`,
    ),
  ]

  const learnings = allLearnings.slice(0, LEARNINGS_LIMIT)

  const domainSkills: DomainSkillEntry[] = orderedSkills.map((skill) => ({
    domain: skill.domain,
    topic: skill.topic,
    confidence: skill.confidence,
    summary: skill.body.trim().split('\n')[0] ?? '',
  }))

  return {
    domainSkills,
    failures,
    policies,
    rules,
    learnings,
    total: learnings.length,
  }
}
