/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * Build script: concatenates individual TOML filter files into a single
 * TypeScript module that exports the concatenated TOML string.
 *
 * Usage: npx tsx scripts/build-filters.ts
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const filtersDir = path.resolve(__dirname, '..', 'src', 'core', 'economy', 'tool-filters', 'filters')
const outputFile = path.resolve(__dirname, '..', 'src', 'core', 'tool-compress', 'builtin-filters.generated.ts')

function build(): void {
  if (!existsSync(filtersDir)) {
    console.error(`Filters directory not found: ${filtersDir}`)
    process.exit(1)
  }

  const files = readdirSync(filtersDir)
    .filter((f) => f.endsWith('.toml'))
    .sort()

  if (files.length === 0) {
    console.warn('No .toml filter files found. Generating empty built-in.')
    writeFileSync(
      outputFile,
      `// Auto-generated by scripts/build-filters.ts — DO NOT EDIT
export const BUILTIN_FILTERS_TOML = ''
`,
    )
    return
  }

  const parts: string[] = []
  for (const file of files) {
    const content = readFileSync(path.join(filtersDir, file), 'utf-8')
    parts.push(content.trimEnd())
  }

  const concatenated = parts.join('\n\n')
  const escaped = concatenated.replace(/\\/g, '\\\\').replace(/`/g, '\\`')

  const generated = `// Auto-generated by scripts/build-filters.ts — DO NOT EDIT
// Built from ${files.length} TOML filter files: ${files.join(', ')}
export const BUILTIN_FILTERS_TOML = \`${escaped}\`
`

  writeFileSync(outputFile, generated)
  console.log(`Built-in filters generated: ${files.length} files → ${outputFile} (${concatenated.length} chars)`)
}

build()
