#!/usr/bin/env node
/**
 * sync-openrouter-prices — fetches current model pricing from OpenRouter API
 * and outputs a TypeScript-compatible pricing snapshot.
 *
 * Usage:
 *   npx tsx scripts/sync-openrouter-prices.ts          # fetch and print
 *   npx tsx scripts/sync-openrouter-prices.ts --write   # fetch and update registry.ts
 *
 * API: https://openrouter.ai/api/v1/models (free tier, no auth needed for list)
 */

const OPENROUTER_MODELS_URL = 'https://openrouter.ai/api/v1/models'

interface OpenRouterModel {
  id: string
  name: string
  pricing: {
    prompt: string // per 1M tokens
    completion: string
  }
  context_length: number
}

async function fetchModels(): Promise<OpenRouterModel[]> {
  const response = await fetch(OPENROUTER_MODELS_URL)
  if (!response.ok) {
    throw new Error(`OpenRouter API returned ${response.status}: ${response.statusText}`)
  }
  const body = (await response.json()) as { data: OpenRouterModel[] }
  return body.data ?? []
}

function formatPricing(models: OpenRouterModel[]): string {
  const lines: string[] = []
  lines.push('// Auto-generated by sync-openrouter-prices')
  lines.push(`// Fetched at: ${new Date().toISOString()}`)
  lines.push('// Source: OpenRouter API (https://openrouter.ai/api/v1/models)')
  lines.push('')
  lines.push('export interface PriceEntry {')
  lines.push('  id: string;')
  lines.push('  inputPerMtok: number;')
  lines.push('  outputPerMtok: number;')
  lines.push('  contextWindow: number;')
  lines.push('}')
  lines.push('')
  lines.push('export const FRESH_PRICES: PriceEntry[] = [')

  for (const m of models.slice(0, 50)) {
    const input = parseFloat(m.pricing.prompt) || 0
    const output = parseFloat(m.pricing.completion) || 0
    lines.push(
      `  { id: "${m.id}", inputPerMtok: ${input}, outputPerMtok: ${output}, contextWindow: ${m.context_length} },`,
    )
  }

  lines.push('];')
  return lines.join('\n')
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const shouldWrite = args.includes('--write')

  try {
    const models = await fetchModels()
    const output = formatPricing(models)

    if (shouldWrite) {
      const fs = await import('node:fs')
      const path = await import('node:path')
      const outPath = path.join(process.cwd(), 'src', 'core', 'llm', 'pricing-snapshot.ts')
      fs.writeFileSync(outPath, output, 'utf-8')
      process.stdout.write(`Written ${models.length} models to ${outPath}\n`)
    } else {
      process.stdout.write(output + '\n')
      process.stdout.write(`\nTotal models: ${models.length}\n`)
    }
  } catch (err) {
    process.stderr.write(`Error: ${err instanceof Error ? err.message : String(err)}\n`)
    process.exit(1)
  }
}

void main()
