// Auto-generated by scripts/build-filters.ts — DO NOT EDIT
// Built from 79 TOML filter files: ansible-playbook.toml, aws-cli.toml, basedpyright.toml, biome.toml, bundle-install.toml, cargo-build.toml, cargo-test.toml, composer-install.toml, curl.toml, df.toml, docker-images.toml, docker-ps.toml, dotnet-build.toml, du.toml, eslint.toml, fail2ban-client.toml, gcc.toml, gcloud.toml, git-diff.toml, git-log.toml, git-status.toml, go-build.toml, go-test.toml, gradle.toml, hadolint.toml, helm.toml, iptables.toml, jira.toml, jj.toml, jq.toml, just.toml, kubectl-get.toml, liquibase.toml, make.toml, markdownlint.toml, mise.toml, mix-compile.toml, mix-format.toml, mypy.toml, next-build.toml, npm-install.toml, nx.toml, ollama.toml, oxlint.toml, ping.toml, pio-run.toml, playwright.toml, poetry-install.toml, pre-commit.toml, prettier.toml, prisma.toml, ps.toml, pytest.toml, quarto-render.toml, rsync.toml, ruff.toml, shopify-theme.toml, skopeo.toml, sops.toml, spring-boot.toml, ssh.toml, stat.toml, swift-build.toml, systemctl-status.toml, task.toml, terraform-plan.toml, tofu-fmt.toml, tofu-init.toml, tofu-plan.toml, tofu-validate.toml, trunk-build.toml, tsc.toml, turbo.toml, ty.toml, uv-sync.toml, vitest.toml, xcodebuild.toml, yadm.toml, yamllint.toml
export const BUILTIN_FILTERS_TOML = `[[filters]]
name = "ansible-playbook"
priority = 50
detect = ["PLAY \\\\[", "TASK \\\\[", "ok: \\\\[", "changed: \\\\[", "failed: \\\\["]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^PLAY RECAP"]
max_lines = 200

# aws cli — keep JSON output, truncate massive responses
[[filters]]
name = "aws-cli"
priority = 60
detect = ["^{", "^\\\\[", "AWS"]

[filters.pipeline]
strip_ansi = true
head_lines = 500

[[filters]]
name = "basedpyright"
priority = 30
detect = ["Pyright", "pyright", "error:", "warning:", "Information:"]

[filters.pipeline]
strip_ansi = true
max_lines = 200
on_empty = "no type errors"

[[filters]]
name = "biome"
priority = 32
detect = ["biome", "linter", "formatter", "analyzer", "Suspicious", "correctness"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 200
max_lines = 300
on_empty = "no lint errors"

[[filters]]
name = "bundle-install"
priority = 50
detect = ["Bundle", "bundle install", "Gemfile", "Fetching", "Installing", "Bundle complete"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^Fetching"]
max_lines = 50
on_empty = "gems up to date"

[[filters]]
name = "cargo-build"
priority = 41
detect = ["Compiling", "error\\\\[E", "warning\\\\[", "aborting due to", "For more information", "Finished "]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  Compiling", "^  Finished"]
keep_lines = ["^error\\\\[", "^warning\\\\[", "^   -->", "^    =", "^  = note", "aborting due to", "error: could not compile", "For more information"]
max_lines = 200
on_empty = "build succeeded"

# cargo test — failures only, strip Compiling/Finished lines
[[filters]]
name = "cargo-test"
priority = 40
detect = ["running \\\\d+ test", "test result:", "FAILED"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^\\\\s+Compiling", "^\\\\s+Finished", "^\\\\s+Downloading"]
max_lines = 200
on_empty = "all tests passed"

[[filters]]
name = "composer-install"
priority = 50
detect = ["composer", "Installing", "Package", "Nothing to install"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50
on_empty = "packages up to date"

# curl — compact HTTP response, JSON auto-detection
[[filters]]
name = "curl"
priority = 70
detect = ["HTTP/", "<html", "<!DOCTYPE", "^{", "^\\\\["]

[filters.pipeline]
strip_ansi = true
head_lines = 300

[[filters]]
name = "df"
priority = 60
detect = ["Filesystem", "Size", "Used", "Avail", "Capacity", "Mounted on", "Mounted"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 160
max_lines = 30

# docker images — compact image list
[[filters]]
name = "docker-images"
priority = 60
detect = ["REPOSITORY", "TAG", "IMAGE ID", "CREATED", "SIZE"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 50

# docker ps — compact container list
[[filters]]
name = "docker-ps"
priority = 60
detect = ["CONTAINER ID", "IMAGE", "COMMAND", "STATUS", "PORTS", "NAMES"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 50

[[filters]]
name = "dotnet-build"
priority = 50
detect = ["Build started", "Build succeeded", "Build FAILED", "error CS\\\\d+", "warning CS\\\\d+"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  ", "^Determining"]
max_lines = 200
on_empty = "build succeeded"

[[filters]]
name = "du"
priority = 60
detect = ["\\\\d+\\\\s+.*/"]

[filters.pipeline]
strip_ansi = true
head_lines = 60

# eslint — group by rule, truncate long messages
[[filters]]
name = "eslint"
priority = 32
detect = ["\\\\d+:\\\\d+\\\\s+error\\\\s+", "\\\\d+:\\\\d+\\\\s+warning\\\\s+", "\\\\d+ problem"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 200
max_lines = 300
on_empty = "no lint errors"

[[filters]]
name = "fail2ban-client"
priority = 60
detect = ["Status", "Banned", "fail2ban"]

[filters.pipeline]
strip_ansi = true
max_lines = 50

[[filters]]
name = "gcc"
priority = 50
detect = ["warning:", "error:", "In file included from", "cc1:"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  "]
max_lines = 200
on_empty = "no warnings or errors"

[[filters]]
name = "gcloud"
priority = 60
detect = ["gcloud", "Listable field", "PROJECT:", "ACCOUNT:"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 150
max_lines = 200

# git diff — compact: only changed lines, strip context
[[filters]]
name = "git-diff"
priority = 10
detect = ["diff --git", "^@@ -\\\\d+,\\\\d+ \\\\+\\\\d+,\\\\d+ @@"]

[filters.pipeline]
strip_ansi = true
max_lines = 500

# git log — one-line per commit, max 50 commits
[[filters]]
name = "git-log"
priority = 15
detect = ["commit [0-9a-f]{7,40}", "Author:", "Date:"]

[filters.pipeline]
strip_ansi = true
replace = [["^commit ([0-9a-f]{7})[0-9a-f]+", "commit $1"], ["^Author: (.*) <.*>", "Author: $1"], ["^Date:\\\\s+", "Date: "]]
max_lines = 80

# git status — compact: drop "nothing to commit", keep branch + changes
[[filters]]
name = "git-status"
priority = 20
detect = ["On branch", "nothing to commit", "Changes", "Untracked files"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^\\\\s+\\\\("]
max_lines = 100
on_empty = "working tree clean"

[[filters]]
name = "go-build"
priority = 41
detect = ["go build", "go vet", "# ", "package ", "undefined:", "cannot find package", "syntax error"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 200
on_empty = "build succeeded"

# go test — failures only, strip ok lines
[[filters]]
name = "go-test"
priority = 40
detect = ["^--- FAIL:", "^ok\\\\s+", "^FAIL\\\\s+", "\\\\d+ passed"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^ok\\\\s+\\\\S+\\\\s+"]
max_lines = 200
on_empty = "all tests passed"

[[filters]]
name = "gradle"
priority = 50
detect = ["BUILD SUCCESSFUL", "BUILD FAILED", ":compile", ":test", "gradle"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^> Task"]
max_lines = 200
on_empty = "build succeeded"

[[filters]]
name = "hadolint"
priority = 50
detect = ["DL\\\\d{4}", "hadolint"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100
on_empty = "no Dockerfile issues"

[[filters]]
name = "helm"
priority = 60
detect = ["NAME:\\\\s+", "LAST DEPLOYED:", "NAMESPACE:", "STATUS:", "CHART:", "REVISION:"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 100

[[filters]]
name = "iptables"
priority = 60
detect = ["Chain", "target", "prot", "opt", "source", "destination"]

[filters.pipeline]
strip_ansi = true
max_lines = 50

[[filters]]
name = "jira"
priority = 50
detect = ["jira", "ISSUE", "SUMMARY", "STATUS", "Priority"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 100

[[filters]]
name = "jj"
priority = 15
detect = ["jj ", "Working copy", "Parent", "Conflict", "Rebased"]

[filters.pipeline]
strip_ansi = true
max_lines = 80

[[filters]]
name = "jq"
priority = 70
detect = ["^{", "^\\\\[", "jq "]

[filters.pipeline]
strip_ansi = true
head_lines = 500

[[filters]]
name = "just"
priority = 50
detect = ["error:", "recipe failed", "Justfile"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100

# kubectl get — compact table output
[[filters]]
name = "kubectl-get"
priority = 60
detect = ["NAME\\\\s+", "READY\\\\s+STATUS", "RESTARTS\\\\s+AGE"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 150
max_lines = 80

[[filters]]
name = "liquibase"
priority = 50
detect = ["Liquibase", "Running Changeset", "liquibase"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100

[[filters]]
name = "make"
priority = 50
detect = ["Makefile:", "make\\\\[\\\\d+\\\\]", "\\\\*\\\\*\\\\* "]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^make\\\\[\\\\d+\\\\]"]
keep_lines = ["^make\\\\[\\\\d+\\\\]: \\\\*\\\\*\\\\*", "error:", "warning:"]
max_lines = 100

[[filters]]
name = "markdownlint"
priority = 32
detect = ["MD\\\\d{3}", "markdownlint"]

[filters.pipeline]
strip_ansi = true
max_lines = 100
on_empty = "no markdown issues"

[[filters]]
name = "mise"
priority = 50
detect = ["mise", "Installed", "Activated"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50

[[filters]]
name = "mix-compile"
priority = 50
detect = ["Compiling", "Generated", "mix compile"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100
on_empty = "compiled successfully"

[[filters]]
name = "mix-format"
priority = 50
detect = ["mix format", "Formatted"]

[filters.pipeline]
strip_ansi = true
on_empty = "all files formatted"

[[filters]]
name = "mypy"
priority = 30
detect = ["mypy", "Success: no issues", "Found \\\\d+ error", "\\\\S+.py:\\\\d+: error:"]

[filters.pipeline]
strip_ansi = true
max_lines = 200
on_empty = "no type issues"

[[filters]]
name = "next-build"
priority = 50
detect = ["Lambda", "Create route", "Route", "next build", "next-env", "✓", "▲"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  Creating", "^  Generating"]
max_lines = 200

# npm install — strip progress, keep added/removed packages + errors
[[filters]]
name = "npm-install"
priority = 50
detect = ["added \\\\d+ package", "removed \\\\d+ package", "up to date", "npm (warn|error|ERR!)"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^\\\\s*$"]
keep_lines = ["^(added|removed|changed|audited) \\\\d+", "^npm (warn|error|ERR!)", "^found \\\\d+ vulnerabilit"]
max_lines = 50
on_empty = "packages up to date"

[[filters]]
name = "nx"
priority = 50
detect = ["NX", ">  NX", "nx run", "graph", "Running target"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 200

[[filters]]
name = "ollama"
priority = 60
detect = ["NAME", "ID", "SIZE", "MODIFIED", "pull", "pulling"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 30

[[filters]]
name = "oxlint"
priority = 32
detect = ["oxlint", "\\\\d+ problems?", "Found"]

[filters.pipeline]
strip_ansi = true
max_lines = 300
on_empty = "no lint errors"

[[filters]]
name = "ping"
priority = 60
detect = ["PING", "bytes from", "packets transmitted", "rtt "]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 20

[[filters]]
name = "pio-run"
priority = 40
detect = ["PlatformIO", "Verbose mode", "Building in", "Linking", "RAM:.*FLASH:"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^Verbose mode"]
head_lines = 80

[[filters]]
name = "playwright"
priority = 40
detect = ["Running \\\\d+ test", " playwright ", "expect\\\\( ", "locator\\\\(", "page\\\\("]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 200

[[filters]]
name = "poetry-install"
priority = 50
detect = ["Creating virtualenv", "Installing", "poetry", "dependencies", "No dependencies to install"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50
on_empty = "dependencies up to date"

[[filters]]
name = "pre-commit"
priority = 50
detect = ["pre-commit", "Trim Trailing Whitespace", "Fix End of Files", "Check Yaml", "Check Toml", "check python"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^-+"]
max_lines = 100
on_empty = "all hooks passed"

# prettier — only list files that need formatting
[[filters]]
name = "prettier"
priority = 50
detect = ["Code style issues", "would be formatted"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^Checking formatting"]
head_lines = 100
on_empty = "all files formatted"

[[filters]]
name = "prisma"
priority = 50
detect = ["Prisma", "prisma", "Datasource", "Generated", "migrate", "environment variables"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100
on_empty = "already up to date"

[[filters]]
name = "ps"
priority = 60
detect = ["PID", "TTY", "TIME", "CMD", "COMMAND"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 30

# pytest — failures only, strip PASSED dots, keep summary
[[filters]]
name = "pytest"
priority = 40
detect = ["=+ test session starts", "collected \\\\d+ item", "FAILED", "PASSED", "ERRORS"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^[.sFx]+$", "^=+ \\\\d+ passed"]
replace = [["FAILED (.+)", "FAIL: $1"], ["ERRORS (.+)", "ERR: $1"]]
max_lines = 200
on_empty = "all tests passed"

[[filters]]
name = "quarto-render"
priority = 50
detect = ["Quarto", "rendering", "output file", "pandoc"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100

[[filters]]
name = "rsync"
priority = 60
detect = ["sending incremental file list", "sent ", "received ", "total size"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50

[[filters]]
name = "ruff"
priority = 32
detect = ["ruff", "Found \\\\d+ error", "\\\\d+ fixable", "\\\\S+.py:\\\\d+:\\\\d+:"]

[filters.pipeline]
strip_ansi = true
max_lines = 300
on_empty = "no lint errors"

[[filters]]
name = "shopify-theme"
priority = 50
detect = ["shopify", "theme", "Uploading", "Processing"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 100

[[filters]]
name = "skopeo"
priority = 50
detect = ["skopeo", "Copying", "Writing", "Manifest"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 30

[[filters]]
name = "sops"
priority = 60
detect = ["sops", "encrypted", "decrypted", "SOPS"]

[filters.pipeline]
strip_ansi = true
max_lines = 30

[[filters]]
name = "spring-boot"
priority = 50
detect = ["Spring Boot", "spring-boot", "APPLICATION FAILED", "Started Application"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  ", "com.", "org.springframework"]
max_lines = 150

[[filters]]
name = "ssh"
priority = 60
detect = ["ssh:", "Permission denied", "Connection refused", "Connection closed", "authenticity of host"]

[filters.pipeline]
strip_ansi = true
max_lines = 30

[[filters]]
name = "stat"
priority = 60
detect = ["File:", "Size:", "Blocks:", "IO Block", "Device:", "Inode:", "Access:"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 20

[[filters]]
name = "swift-build"
priority = 50
detect = ["swift build", "Compiling", "Build complete", "Build failed", "error:"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  Compiling"]
max_lines = 200
on_empty = "build succeeded"

[[filters]]
name = "systemctl-status"
priority = 60
detect = ["systemctl", "Loaded:", "Active:", "Main PID:", "Status:", "since"]

[filters.pipeline]
strip_ansi = true
max_lines = 30

[[filters]]
name = "task"
priority = 50
detect = ["task ", "Task ", "taskwarrior", "task add", "task list"]

[filters.pipeline]
strip_ansi = true
truncate_lines_at = 120
max_lines = 100

# terraform plan — compact: keep resource changes, strip noise
[[filters]]
name = "terraform-plan"
priority = 50
detect = ["Terraform will perform", "Plan:", "No changes"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^Reading...", "^Refreshing state"]
replace = [["\\\\s+=>\\\\s+", " → "]]
max_lines = 400

[[filters]]
name = "tofu-fmt"
priority = 50
detect = ["OpenTofu fmt", "formatted"]

[filters.pipeline]
strip_ansi = true
on_empty = "all files formatted"

[[filters]]
name = "tofu-init"
priority = 50
detect = ["Initializing", "OpenTofu initialized", "Terraform has been successfully initialized"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^Initializing"]
max_lines = 50
on_empty = "already initialized"

[[filters]]
name = "tofu-plan"
priority = 50
detect = ["OpenTofu will perform", "Plan:", "No changes", "Tofu has compared"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^Reading...", "^Refreshing state"]
replace = [["\\\\s+=>\\\\s+", " -> "]]
max_lines = 400

[[filters]]
name = "tofu-validate"
priority = 50
detect = ["Success!", "Error:", "OpenTofu validation"]

[filters.pipeline]
strip_ansi = true
max_lines = 100
on_empty = "configuration is valid"

[[filters]]
name = "trunk-build"
priority = 50
detect = ["trunk build", "Finished", "Compiling", "cargo build"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^  Compiling", "^  Finished"]
max_lines = 50

# tsc — TypeScript compiler errors grouped by file
[[filters]]
name = "tsc"
priority = 30
detect = ["error TS\\\\d+:", "Found \\\\d+ error"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^node_modules/"]
max_lines = 200
on_empty = "no type errors"

[[filters]]
name = "turbo"
priority = 50
detect = ["turbo", "turbo build", "turbo dev", "• Packages"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 200

[[filters]]
name = "ty"
priority = 50
detect = ["error:", "warning:", "ty:"]

[filters.pipeline]
strip_ansi = true
max_lines = 100
on_empty = "no typos found"

[[filters]]
name = "uv-sync"
priority = 50
detect = ["Resolved", "Prepared", "Installed", "uv sync", "Unchanged"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50
on_empty = "environment up to date"

# vitest/jest — failures only, strip PASS lines, keep summary
[[filters]]
name = "vitest"
priority = 40
detect = ["Tests\\\\s+\\\\d+ failed", "FAIL\\\\s+", "✓|✗|PASS|FAIL", "Test Files"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^\\\\s*✓", "^\\\\s*PASS"]
replace = [["Tests\\\\s+(\\\\d+) failed \\\\| (\\\\d+) passed", "FAILURES: $1 | TOTAL: $1+$2"]]
max_lines = 200
on_empty = "all tests passed"

[[filters]]
name = "xcodebuild"
priority = 50
detect = ["xcodebuild", "Build settings", "\\\\*\\\\* BUILD", "error:", "warning:", "CompileC", "Ld "]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$", "^\\\\t", "^    "]
max_lines = 200
on_empty = "build succeeded"

[[filters]]
name = "yadm"
priority = 20
detect = ["yadm", "Already up to date", "dotfiles"]

[filters.pipeline]
strip_ansi = true
strip_lines = ["^$"]
max_lines = 50

[[filters]]
name = "yamllint"
priority = 32
detect = ["yamllint", "error:", "warning:"]

[filters.pipeline]
strip_ansi = true
max_lines = 100
on_empty = "no YAML issues"`
