/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 */

import { Command } from 'commander'
import { writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { openStoreOrFail } from '../open-store.js'
import { getFrequencies, getTotalCommands } from '../../core/observability/cmd-tracker.js'
import { createLogger } from '../../core/utils/logger.js'
import { createCliOutput } from '../shared/cli-output.js'
import { getRegisteredCommandNames } from '../command-registry.js'

const log = createLogger({ layer: 'cli', source: 'usage-cmd.ts' })

const WRAPPER_TEMPLATE = `/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 */

import { Command } from 'commander'
import { spawnSync } from 'node:child_process'
import { createLogger } from '../../core/utils/logger.js'
import { createCliOutput } from '../shared/cli-output.js'

const log = createLogger({ layer: 'cli', source: '{{SOURCE}}' })

export function {{FUNC_NAME}}(): Command {
  log.info('{{COMMAND}} command registered')
  const cmd = new Command('{{COMMAND}}')
    .description('{{DESC}}')
    .allowUnknownOption(true)
    .allowExcessArguments(true)
    .option('-d, --dir <dir>', 'Project directory', '', process.cwd())
  cmd.action(function (this: Command) {
    const out = createCliOutput('{{COMMAND}}')
    const rawArgs = process.argv.slice(process.argv.indexOf('{{COMMAND}}') + 1)
    const result = spawnSync('{{NATIVE}}', rawArgs, {
      cwd: cmd.opts().dir || process.cwd(),
      stdio: 'inherit',
    })
    if (result.status === 0) {
      out.ok({ code: result.status })
    } else {
      out.fail('CMD_FAILED', \`{{NATIVE}} failed with code \${result.status}\`, { code: result.status })
    }
  })
  return cmd
}
`

const INDEX_INSERTION = `
  {
    name: '{{COMMAND}}',
    description: '{{DESC}}',
    loader: () => import('./commands/{{COMMAND}}-cmd.js').then((m) => m.{{FUNC_NAME}}()),
  },`

function generateWrapper(
  command: string,
  _args: string,
): { fileName: string; content: string; indexEntry: string; funcName: string } {
  const funcName = `${command.replace(/[-]/g, '_')}Command`
  const desc = `Wrapper for ${command} — auto-generated by agf usage wrap`
  const source = `${command}-cmd.ts`

  const content = WRAPPER_TEMPLATE.replace(/\{\{COMMAND\}\}/g, command)
    .replace(/\{\{FUNC_NAME\}\}/g, funcName)
    .replace(/\{\{DESC\}\}/g, desc)
    .replace(/\{\{NATIVE\}\}/g, command)
    .replace(/\{\{SOURCE\}\}/g, source)

  const indexEntry = INDEX_INSERTION.replace(/\{\{COMMAND\}\}/g, command)
    .replace(/\{\{DESC\}\}/g, desc)
    .replace(/\{\{FUNC_NAME\}\}/g, funcName)

  return { fileName: source, content, indexEntry, funcName }
}

/** Builds the `agf usage` CLI command (Commander definition). */
export function usageCommand(): Command {
  log.info('usage command registered')
  const cmd = new Command('usage').description(
    'Command usage analytics: track frequency, report trends, auto-generate wrappers',
  )

  cmd
    .command('report')
    .description('Show most-used commands and suggest missing wrappers')
    .option('-d, --dir <dir>', 'Project directory', process.cwd())
    .option('--top <n>', 'Number of top commands to show', '10')
    .action((opts: { dir: string; top: string }) => {
      const out = createCliOutput('usage.report')
      const store = openStoreOrFail(opts.dir, { requireExisting: true })
      try {
        const project = store.getProject()
        if (!project) {
          out.err('NOT_FOUND', 'No project found — run agf init first.')
          return
        }
        const topN = Math.max(1, parseInt(opts.top, 10) || 10)
        const freqs = getFrequencies(store.getDb(), project.id, topN)
        const total = getTotalCommands(store.getDb(), project.id)

        if (freqs.length === 0) {
          out.ok({
            total,
            top: [],
            hint: 'No commands tracked yet. Run: agf exec "your-command" --track',
          })
          return
        }

        const registered = new Set(getRegisteredCommandNames())

        const top = freqs.map((f) => ({
          command: f.command,
          count: f.count,
          avgMs: Math.round(f.avgDurationMs),
          lastUsed: new Date(f.lastUsed).toISOString(),
          hasWrapper: registered.has(f.command),
          suggestion: registered.has(f.command)
            ? null
            : `agf usage wrap ${f.command}  (no wrapper yet — auto-generate)`,
        }))

        const unwrapped = top.filter((t) => !t.hasWrapper)

        out.ok({
          total,
          top,
          unwrappedCount: unwrapped.length,
          hint:
            unwrapped.length > 0
              ? `${unwrapped.length} unwrapped command(s) detected. Run: agf usage wrap <command>`
              : 'All top commands have wrappers.',
        })
      } finally {
        store.close()
      }
    })

  cmd
    .command('wrap <command> [args]')
    .description('Auto-generate an agf wrapper for a native command')
    .option('-d, --dir <dir>', 'Project directory', process.cwd())
    .option('--apply', 'Write the generated wrapper to disk', false)
    .action((command: string, args: string, opts: { dir: string; apply?: boolean }) => {
      const out = createCliOutput('usage.wrap')
      const gen = generateWrapper(command, args ?? '')

      if (!opts.apply) {
        out.ok({
          command,
          preview: true,
          fileName: gen.fileName,
          content: gen.content.slice(0, 500),
          hint: 'Use --apply to write this file and register the command.',
        })
        return
      }

      const cmdsDir = join(opts.dir, 'src', 'cli', 'commands')
      if (!existsSync(cmdsDir)) {
        mkdirSync(cmdsDir, { recursive: true })
      }

      const filePath = join(cmdsDir, gen.fileName)
      if (existsSync(filePath)) {
        out.ok({ command, written: false, message: `${filePath} already exists.` })
        return
      }

      writeFileSync(filePath, gen.content, 'utf-8')

      out.ok({
        command,
        written: true,
        filePath,
        indexEntry: gen.indexEntry,
        hint: `Wrapper written to ${gen.fileName}. Add this to src/cli/index.ts commands array:\n${gen.indexEntry}`,
      })
    })

  return cmd
}
