/*!
 * SPDX-License-Identifier: Apache-2.0
 * Copyright © 2026 Diego Lima Nogueira de Paula
 *
 * GENERATED — do not edit. Run `npm run gen:command-surface`.
 *
 * The full agf command surface, flattened, so RAG-IN can retrieve any of it. Derived from the
 * live commander tree by scripts/gen-command-surface.mts; kept honest by
 * src/tests/command-tree.test.ts, which walks the CLI and fails when this file drifts.
 */

/** One invocable command path (no `agf` prefix) and the intent RAG-IN ranks against. */
export interface SurfaceEntry {
  path: string
  description: string
}

export const COMMAND_SURFACE: readonly SurfaceEntry[] = [
  { path: "ac", description: "AC quality tools (harden weak ACs to GWT)" },
  { path: "ac harden", description: "Rewrite weak ACs on a node to Given-When-Then skeleton" },
  { path: "ac lint", description: "Flag vague/untestable quality terms in a node's acceptance criteria" },
  { path: "ac nfr", description: "Inject a measurable NFR AC stub into a node" },
  { path: "ac suggest", description: "Suggest standard edge-case ACs (empty_input/error_path/boundary/concurrency) for a node" },
  { path: "adr", description: "Architecture Decision Records (create, list)" },
  { path: "adr create", description: "Cria um ADR numerado em markdown" },
  { path: "adr list", description: "Lista os ADRs existentes" },
  { path: "agent", description: "Agent role management: create (scaffold TOML) | list (built-in + project)" },
  { path: "agent create", description: "Scaffold a new AgentRole entry in .agf/agents.toml" },
  { path: "agent list", description: "List all agent roles (built-in + project-local)" },
  { path: "ant", description: "Worktree-por-formiga: spawn|list|rm cria worktree isolado por agente, todas as formigas no MESMO grafo central (AGF_GRAPH_ROOT)" },
  { path: "ant list", description: "Lista os worktrees de formiga vivos da colônia" },
  { path: "ant rm", description: "Remove o worktree da formiga (a branch ant/<id> é preservada)" },
  { path: "ant spawn", description: "Spawnar formiga: cria (ou reusa) o worktree da formiga em <repo>-ants/<id> e devolve os exports prontos" },
  { path: "approval", description: "Approval token lifecycle (create → grant → verify → consume/revoke, delegation chain)" },
  { path: "approval check", description: "Run the full lifecycle of an approval token in one call: create → grant → verify → consume (or --revoke)" },
  { path: "approval wait", description: "Poll `.workflow-approvals/<taskId>.json` for a human-dropped {approved:true} signal file; blocks until approved or timeout" },
  { path: "artifacts", description: "Artefatos estruturados de subtask (diff/file/interface/decision/note) — v11 context-pollination" },
  { path: "artifacts add", description: "Registra um artefato de subtask (dedup por conteúdo)" },
  { path: "artifacts get", description: "Busca um artefato pelo id" },
  { path: "artifacts list", description: "Lista artefatos por nó ou por épico" },
  { path: "audit", description: "Consulta o audit trail de tool calls (queryAuditLog/formatAuditEntry)" },
  { path: "audit redact", description: "Redacta segredos (API keys, tokens, senhas) de um texto ou JSON (redactSecrets)" },
  { path: "audit tool-usage", description: "Uso de tokens por MCP tool (ToolTokenStore.getUsageStats) — evidência para o deprecation gate" },
  { path: "autopilot", description: "Loop autônomo com guardrails: next → in_progress → DoD → done|escalate (WIP=1)" },
  { path: "backfill-provenance", description: "Attribute nodes missing source_file by inheriting the closest ancestor along parent_of edges" },
  { path: "brief", description: "Generate the delegation brief (ExecutorBrief spec) for a task node — markdown | json | claude-prompt" },
  { path: "build", description: "Orquestra a entrega: PRD → grafo → decompõe → autopilot → entrega (máquina de estados)" },
  { path: "cache", description: "Prompt-cache management and statistics (cache stats)" },
  { path: "cache live-zone", description: "Frozen/live boundary for a JSON message array — which messages are cacheable vs must stay live" },
  { path: "cache plan-store", description: "Plan template cache operations" },
  { path: "cache plan-store list", description: "List stored plan templates with metadata" },
  { path: "cache stats", description: "Show cache hit rate, token savings, and estimated USD savings from llm_call_ledger" },
  { path: "calibrate", description: "Calibra o limiar do portão RAG por score×saved (lê economy_lever_ledger)" },
  { path: "caste", description: "Colony caste taxonomy: list|show (model_tier, max_complexity, task_types)" },
  { path: "caste list", description: "List all 4 castes with model_tier, max_complexity, and task_types" },
  { path: "caste show", description: "Show definition for a specific caste (minima|pequena|media|soldado)" },
  { path: "certainty", description: "Delivery Certainty — verdict \"is it REALLY done?\" with the means (pillars) explicit" },
  { path: "changelog", description: "Generate Keep-a-Changelog sections from conventional commits in a git ref range" },
  { path: "changelog generate", description: "Generate a changelog section for commits in a git ref range" },
  { path: "check", description: "Roda Definition of Done + aderência TDD numa task (guardrail do BUILD)" },
  { path: "claims", description: "List active agent lease claims on graph tasks (read-only visibility)" },
  { path: "code", description: "Code intelligence: index, search, navigate, impact analysis, LSP diagnostics" },
  { path: "code affected", description: "Show which test files reference symbols in the given file" },
  { path: "code callees", description: "List all callees (outgoing relations) of the symbol at file:line" },
  { path: "code callers", description: "List all callers (incoming relations) of the symbol at file:line" },
  { path: "code context", description: "Enriched context for a symbol: relevant project memories + code graph data, combined" },
  { path: "code contract-drift", description: "Compare a 'contract' node's declared method signatures (graph side, stored under node.metadata.methods as Record<name, signature>) against the implementation in <file> (code side, parsed via the TS analyzer) — reports added/removed/changed methods." },
  { path: "code deep-modules", description: "Classify source files by depth ratio (exported LOC / total LOC) — Ousterhout deep-module heuristic. Flags shallow modules (wide interface, thin implementation) as refactor candidates." },
  { path: "code def", description: "Find the definition location of a symbol by name" },
  { path: "code impact", description: "Analyze blast radius: symbols affected by changes in a file" },
  { path: "code index", description: "Index the project codebase (symbols + relations via tree-sitter)" },
  { path: "code inspect-config", description: "Structural preview of a config/schema file — dispatches by extension/basename to a deterministic parser (yaml, toml, sql, graphql, terraform, env, Makefile, Dockerfile). Zero LLM calls." },
  { path: "code processes", description: "Detect execution entry points (exported functions/methods with no incoming calls) and trace their call chains — a map of what actually runs in this codebase." },
  { path: "code refs", description: "List all references to a symbol by name" },
  { path: "code seams", description: "Classify each file import into a seam category (in-process, local-substitutable, remote-owned, true-external) — surfaces true-external deps that need an adapter wrapper before core code depends on them." },
  { path: "code search", description: "Search code symbols via FTS5 (full-text), with optional TF-IDF reranking and module grouping" },
  { path: "code skeleton-plan", description: "Detect polymorphic supertypes (>=3 implementations) and report an adaptive skeletonize plan — dry-run, no file writes. Flags off-spine sibling bodies that can be stubbed to shrink repo-map token cost." },
  { path: "code sync-check", description: "Detect drift between graph nodes and the code index — stale sourceRefs, missing testFiles, done tasks without test references. Run `agf code index` first for accurate results." },
  { path: "code zoom-out", description: "Caller-graph overview: fan-in/fan-out per file from relative imports — surfaces central modules (high fan-in), leaves and islands (unreferenced), plus a mermaid digraph." },
  { path: "colony-health", description: "Show colony health status and snapshot history (--history)" },
  { path: "commit-scope", description: "Commita EXATAMENTE os arquivos declarados do node (pathspec) — staged alheio no index permanece intacto" },
  { path: "compress", description: "Compressor de saída de ferramenta: filtros, discover, teste" },
  { path: "compress discover", description: "Saídas sem filtro registradas (rode o agente com AGF_COMPRESS_DISCOVER=1)" },
  { path: "compress filters", description: "Lista os filtros ativos (built-in + custom de AGF_COMPRESS_FILTERS)" },
  { path: "compress run", description: "Run a command and compress its stdout, or compress stdin (PostToolUse hook). Usage: 'agf compress run -- <cmd>' or pipe: 'cmd | agf compress run --stdin'" },
  { path: "compress test", description: "Mostra qual filtro casaria e quanto comprimiria a saída de <file>" },
  { path: "compress trajectory", description: "Compress a conversation trajectory JSON (array of turns), removing obsolete tool outputs and resolved errors" },
  { path: "config", description: "Get, set, or list project config settings" },
  { path: "config get", description: "Get a config value" },
  { path: "config list", description: "List all config settings" },
  { path: "config set", description: "Set a config value" },
  { path: "constitution", description: "Manage project principles (list, check)" },
  { path: "context", description: "Emite o context-pack (compact) de um nó (tool MCP `context`)" },
  { path: "context detail", description: "Detalhe de um nó: contagem de filhos e arestas" },
  { path: "context git", description: "Estado git compacto: branch, arquivos dirty, commits recentes" },
  { path: "context health", description: "Compute context health score (0-100): size, freshness, relevance dimensions" },
  { path: "context summary", description: "Resumo do grafo: contagem por tipo/status, total de nós, próxima task" },
  { path: "cycle-repair", description: "Detecta ciclos de dependência e propõe correções (ADR-0061) — report-only por padrão" },
  { path: "daemon", description: "Inspect and clean up mcp-graph daemons" },
  { path: "daemon list", description: "List daemon state directories and their status (read-only)" },
  { path: "daemon ping", description: "Round-trip a request through an app-server WebSocket URL (e.g. ws://localhost:4555)" },
  { path: "daemon prune", description: "Kill orphaned daemons (workspace gone) and remove stale state dirs" },
  { path: "daemon serve-unix", description: "Start a Unix-socket app-server echo listener at <path> (foreground; Ctrl-C to stop)" },
  { path: "daemon serve-ws", description: "Start a WebSocket app-server echo listener at <port> (foreground; Ctrl-C to stop)" },
  { path: "daemon start", description: "Start the mcp-graph daemon in background" },
  { path: "daemon status", description: "Check if the mcp-graph daemon is running for this workspace" },
  { path: "daemon stop", description: "Stop the mcp-graph daemon for this workspace" },
  { path: "dashboard", description: "Start the agf web dashboard (Graph + Economy SPA + /api/v1)" },
  { path: "dataset", description: "Datasets persistentes para avaliação — manuais, de traces reais, ou de decision logs" },
  { path: "dataset capture-decisions", description: "Cria um dataset a partir de todo o decision_log" },
  { path: "dataset capture-traces", description: "Cria um dataset a partir de execution_traces existentes" },
  { path: "dataset create", description: "Cria um dataset vazio" },
  { path: "dataset experiment", description: "Experimentos de hypothesis testing sobre datasets (Fisher 1925 / Neyman-Pearson 1933)" },
  { path: "dataset experiment compare", description: "Compara dois experimentos" },
  { path: "dataset experiment run", description: "Cria e executa um experimento imediatamente (targetFn default: identity)" },
  { path: "dataset experiment show", description: "Mostra um experimento por ID" },
  { path: "dataset show", description: "Mostra um dataset + suas entradas" },
  { path: "decompose", description: "Detecta tasks grandes demais e sugere subtasks atômicas (anti-one-shot)" },
  { path: "deliver", description: "Pedido → PRD → grafo → build TDD, autônomo e econômico (texto, --file ou --image)" },
  { path: "docs", description: "Inspect the local docs cache (list/search/sync) or generate living graph docs (`docs generate`)" },
  { path: "docs generate", description: "Generate living, agent-oriented docs from the graph (deterministic, zero tokens)" },
  { path: "docs list", description: "List cached library docs" },
  { path: "docs manifest", description: "Introspect tools/routes/docs into a manifest (optionally writing it to disk)" },
  { path: "docs search", description: "Full-text search cached library docs" },
  { path: "docs stack", description: "Detect the project's stack (package.json/requirements.txt/go.mod) for docs sync targeting" },
  { path: "docs sync", description: "Fetch a library doc via Context7 and upsert it into the docs cache" },
  { path: "doctor", description: "Validate the execution environment" },
  { path: "done", description: "Complete task: DoD check + run tests + memory store + mark done + suggest next" },
  { path: "dream", description: "REM-inspired knowledge consolidation cycles (start/status/history/cancel)" },
  { path: "dream cancel", description: "Cancel any running dream cycle" },
  { path: "dream history", description: "Show past dream cycles" },
  { path: "dream start", description: "Start a complete dream cycle (NREM → REM → Boost)" },
  { path: "dream status", description: "Show current (latest) dream cycle status" },
  { path: "economy", description: "Toggle/list opt-in bio/math token-economy levers" },
  { path: "economy ab-lever", description: "Run an on/off token-cost A/B per lever (comma-separated) over a task-set (comma-separated) via runLeverAb — mode:\"delegated\" until a live executor is wired" },
  { path: "economy allocate-budget", description: "Reallocate a token budget across graph nodes by size^0.75 (Kleiber, opt-in `budget_kleiber` lever)" },
  { path: "economy list", description: "List levers with enabled flag + cumulative saved tokens (JSON)" },
  { path: "economy measure-input", description: "Measure the input-payload cut of ONE lever on ONE task via measureInputLever — no provider call, no cost" },
  { path: "economy off", description: "Disable a lever" },
  { path: "economy on", description: "Enable a lever" },
  { path: "economy param", description: "Set a numeric parameter on a lever (e.g. \"agf economy param forage_stop epsilon 0.2\")" },
  { path: "economy pheromone-sim", description: "Replay stigmergy deposits (JSON array of {key,amount?,atMs}) through the in-process PheromoneTrail and report decayed strengths at --now" },
  { path: "economy pipeline", description: "List economy pipeline stages (Booster→Cache→Tier→Batch→Tiered→...→LLM) with enabled flag" },
  { path: "economy preset", description: "Toggle a named lever bundle on/off (e.g. \"build\" = loss-safe input-side cutters)" },
  { path: "economy schema", description: "Expose economy-types.ts Zod schemas as JSON Schema (omit name to list available schemas)" },
  { path: "economy shadow-sim", description: "Replay a sequence of task calls (JSON array of {lever,baselineTokens,actualTokens,nodeId?}) through the in-process ShadowSampler (1-in-N dual-path baseline) and report which were sampled + mean baseline per lever" },
  { path: "economy view", description: "Render the economy panel as an HTML fragment (data.html) from the current ledger" },
  { path: "edge", description: "CRUD de arestas (add/rm/ls) — zero MCP" },
  { path: "edge add", description: "Cria uma aresta entre dois nós" },
  { path: "edge ls", description: "Lista arestas (opcionalmente filtradas por nó)" },
  { path: "edge rm", description: "Remove uma aresta" },
  { path: "eval", description: "Roda a suíte de cenários reais → scorecard (resolve% × custo-por-sucesso × tokens × latência)" },
  { path: "exec", description: "Executa comandos agf em sequência (composição CLI)" },
  { path: "exec chain", description: "Executa um pipeline de comandos agf separados por ;" },
  { path: "exec pipe", description: "Executa um comando agf e retorna o resultado JSON" },
  { path: "exec safe", description: "Safe Mode (M8): enforced production pipeline — brief→start→blast→check→done.\nEach step has mandatory gates: status validation, test pass, DoD, file-modification proof.\nFails fast at the FIRST broken gate — no partial state left behind." },
  { path: "exec-policy", description: "Utilitários de aprovação de comandos shell (ShellEscalation) — `exec-policy check <command>`" },
  { path: "exec-policy check", description: "Evaluate a shell command against the exec approval-escalation policy" },
  { path: "export", description: "Serializa o grafo como JSON, CSV ou diagrama Mermaid (tool MCP `export`)" },
  { path: "federation", description: "Federação de conhecimento entre projetos (peer registry + tick)" },
  { path: "federation add-peer", description: "Registra (ou atualiza) um peer" },
  { path: "federation disable", description: "Desabilita um peer (pula no próximo tick)" },
  { path: "federation enable", description: "Habilita um peer (roda no próximo tick)" },
  { path: "federation export-learning", description: "Exporta o bundle de aprendizado operacional (pheromones+outcomes+decisões)" },
  { path: "federation learn", description: "Importa aprendizado operacional de um bundle.json ou do dir de outro projeto agf" },
  { path: "federation list", description: "Lista peers registrados" },
  { path: "federation remove-peer", description: "Remove um peer" },
  { path: "federation tick", description: "Pull knowledge de todos os peers habilitados via learnFromProject" },
  { path: "flow", description: "Fórmula do flow (Φ/λ_flow): liga, desliga e inspeciona a diluição de contexto" },
  { path: "flow off", description: "Desliga o flow no projeto (preserva overrides do flow_config)" },
  { path: "flow on", description: "Liga o flow no projeto (preserva overrides do flow_config)" },
  { path: "flow status", description: "Estado efetivo do flow: enabled, Φ, streak, λ_flow e telemetria acumulada" },
  { path: "forecast", description: "Previsão de ETA do backlog com 95% CI (velocity trend + regressão linear)" },
  { path: "forecast capacity", description: "Calibração de capacidade do sprint atual vs velocity histórica (±10% tolerância)" },
  { path: "gaps", description: "Detect SHAPE completeness gaps + emit driver-agnostic enrichment requests (zero MCP, ~0 token)" },
  { path: "gate", description: "Run phase-readiness gates (design, review, handoff, deploy, listening, next, all)" },
  { path: "gc", description: "Garbage-collect orphan ai-shadow/* worktrees and branches" },
  { path: "gearshift", description: "Manual gear (1-4) for model/effort — reflects in ~/.claude/settings.json" },
  { path: "gearshift auto", description: "Liga/desliga o modo automático (off = manual, gearshift set sobrepõe)" },
  { path: "gearshift down", description: "Desce um rung de gear (piso em 1)" },
  { path: "gearshift set", description: "Fixa um gear (1-4) manualmente — sobrepõe o modo auto" },
  { path: "gearshift status", description: "Mostra o gear/tier/model/effort atual e se o modo auto está ligado" },
  { path: "gearshift up", description: "Sobe um rung de gear (cap em 4)" },
  { path: "generate-prd", description: "Gera um PRD.md com AC testável por task; --import já vira grafo (tasks recebem AC extraído/sintetizado; report inclui data.acCoverage)" },
  { path: "genesis", description: "Criar um projeto do zero: ideia → grafo → primeiro brief em 1 round-trip (init → generate_prd → import_prd → decompose → gaps → brief)" },
  { path: "guardrail", description: "Guardrails de qualidade persistidos — pre/post checks com fail_open/fail_closed (Meyer 1986)" },
  { path: "guardrail by-trace", description: "Lista as execuções de guardrail de um trace" },
  { path: "guardrail pass-rate", description: "Taxa de aprovação (0-1) dos guardrails de um trace" },
  { path: "guardrail record", description: "Registra uma execução de guardrail" },
  { path: "harness", description: "Scan harnessability score (type, test, docs, architecture, naming, errors, context)" },
  { path: "hash-content", description: "Stable content hash for a TS/JS file — comments/whitespace-noise-free (ADR-0048)" },
  { path: "heal", description: "Self-healing do grafo (MAPE-K): detecta e cura, persistindo o resultado" },
  { path: "help", description: "Índice amigável de comandos (visão geral + primeiros passos)" },
  { path: "hooks", description: "Inspect the 28-point hook taxonomy (list/test/discover)" },
  { path: "hooks add", description: "Scaffolds a hook entry into .mcp-graph/hooks.json" },
  { path: "hooks add-shell", description: "Generate default shell hooks (agf hook <sub>) for CLIs without native hook support, merged into hooks.json" },
  { path: "hooks discover", description: "Lista canais da taxonomia sem handler registrado" },
  { path: "hooks import-aider", description: "Import .aider.conf.yml (lint-cmd/test-cmd) hook blocks into .mcp-graph/hooks.json" },
  { path: "hooks import-claude-code", description: "Import ~/.claude/settings.json hook blocks into .mcp-graph/hooks.json" },
  { path: "hooks import-cline", description: "Report Cline (VS Code) MCP servers configured in the user settings.json — no hook lifecycle to import" },
  { path: "hooks import-codex", description: "Import ~/.codex/config.toml [hooks] blocks into .mcp-graph/hooks.json" },
  { path: "hooks import-continue", description: "Report Continue.dev MCP servers configured in ~/.continue/config.json — no hook lifecycle to import" },
  { path: "hooks import-copilot", description: "Import .github/hooks/*.{json,toml} blocks into .mcp-graph/hooks.json" },
  { path: "hooks import-cursor", description: "Persist .cursor/rules content as a project memory (cursor-rules) so it surfaces in RAG search" },
  { path: "hooks import-opencode", description: "Import ~/.config/opencode/config.toml [hooks] blocks into .mcp-graph/hooks.json" },
  { path: "hooks install", description: "Install mcp-graph hooks into .claude/settings.local.json (SessionStart/PreToolUse/PostToolUse/Stop)" },
  { path: "hooks list", description: "Lista os 28 pontos da taxonomia: ponto → canal → módulo-owner" },
  { path: "hooks stats", description: "Handler call stats: count, p50/p95 duration, error count, last error, circuit state" },
  { path: "hooks status", description: "Show installed mcp-graph hooks + config drift vs the current installer version" },
  { path: "hooks test", description: "Dry-fire de um canal com payload de fixture" },
  { path: "hooks tool-test", description: "Dry-fire a per-tool lifecycle hook (PreToolUse/PostToolUse/PostToolUseFailure) against a fixture payload" },
  { path: "hooks uninstall", description: "Remove mcp-graph hooks from .claude/settings.local.json, leaving other hooks untouched" },
  { path: "immune", description: "Sistema Imune: detecção e recuperação Danger Theory em código-fonte" },
  { path: "implementer", description: "Transição de lifecycle atribuída a um agente (start/progress/done), com validação de boundary" },
  { path: "import-graph", description: "Funde um grafo JSON exportado no projeto (tool MCP `import_graph`)" },
  { path: "import-prd", description: "Importa um PRD (.md/.txt/.pdf/.html) para o grafo — tasks recebem AC (extraído ou sintetizado); report inclui data.acCoverage (fase SHAPE)" },
  { path: "init", description: "Initialize agf: setup → neural → doctor → serve" },
  { path: "insights", description: "Deterministic graph analytics (DORA, bottlenecks, phases)" },
  { path: "insights auto-ready", description: "Tasks no backlog que já satisfazem todos os critérios de \"ready\" (sprint + AC + deps resolvidas)" },
  { path: "insights behavioral", description: "Métricas comportamentais: autonomia + resiliência (MTTR)" },
  { path: "insights bottlenecks", description: "Detecção de gargalos" },
  { path: "insights calibration", description: "Calibração de estimativa por xpSize (avg_delta/bias_pct/confidence)" },
  { path: "insights cfd", description: "Série temporal do Cumulative Flow Diagram (snapshots capturados via flow-snapshot)" },
  { path: "insights dora", description: "Métricas DORA" },
  { path: "insights evolution", description: "Nodes regenerados no ciclo de vida (evolution_count/evolution_reason)" },
  { path: "insights flow", description: "Flow A/B verdict (flow_on vs flow_off token savings)" },
  { path: "insights flow-snapshot", description: "Captura o snapshot de fluxo de hoje (backlog/ready/in_progress/blocked/done) para o CFD" },
  { path: "insights kr", description: "KR estruturado (target/current/unit/attainment) para cada épico do grafo" },
  { path: "insights layers", description: "Classificação determinística (L0-L4) de cada tool MCP + distribuição por camada" },
  { path: "insights lifecycle-health", description: "9-phase PRD lifecycle health for an epic — persists a rolling snapshot + success rate" },
  { path: "insights phases", description: "Distribuição de tasks por fase" },
  { path: "insights policy", description: "Divergência de roteamento de provider (top rules, preferred providers) via policy_observations" },
  { path: "insights quality", description: "Burndown de gaps por kind + delta vs snapshot anterior" },
  { path: "insights risks", description: "Stale open risks (findings that have not been triaged)" },
  { path: "insights skills", description: "Recomendação de skills com base na fase atual do ciclo de vida" },
  { path: "insights spectra", description: "5 behaviour spectra: autonomy/precision/self_learning/self_healing/memory" },
  { path: "insights sprint-health", description: "Grade de saúde do sprint (healthy/at_risk/critical) — burndown, blocked ratio, AC, harness delta" },
  { path: "insights sprint-progress", description: "Burndown, tendência de velocidade, blockers, caminho crítico e ETA (opcional: --sprint)" },
  { path: "insights summary", description: "Resumo de fluxo" },
  { path: "insights wip", description: "WIP count and alert" },
  { path: "install-neural", description: "Install ONNX runtime + model to enable neural RAG embeddings" },
  { path: "kanban", description: "Render the deterministic Kanban board (status columns, WIP, flow metrics)" },
  { path: "kanban validate-move", description: "Dry-run check for a card move: advisory warnings on unresolved deps / WIP overflow (never blocks)" },
  { path: "knowledge-compile", description: "Ingere/compila uma source em CompiledPage (structured + links + version)" },
  { path: "knowledge-learn", description: "Importa conhecimento de outro projeto's graph.db (memories/decisions/patterns)" },
  { path: "knowledge-lint", description: "Lint read-only do knowledge store (findings sem deleção)" },
  { path: "learn-eval", description: "Relatório de precisão do aprendizado ACO/bandit (accuracy, regret, Brier, ECE, precisionScore)" },
  { path: "learning", description: "Aprendizado persistido: performance por agente, roteamento, export" },
  { path: "learning compile", description: "Compila decisões repetidas e bem-sucedidas em regras determinísticas (fast-path zero-token)" },
  { path: "learning distill", description: "Distila traces de raciocínio (STaR, Opus→Haiku) em decisões compiladas no fast-path zero-token" },
  { path: "learning explain", description: "Explica a decisão de roteamento (breakdown)" },
  { path: "learning export", description: "Exporta todos os registros de learning (JSON)" },
  { path: "learning lookup", description: "Consulta o fast-path zero-token (replay de decisão compilada, sem chamar LLM)" },
  { path: "learning route", description: "Decisão de roteamento de agente baseada no histórico" },
  { path: "learning stats", description: "Estatísticas de performance por agente (persistidas)" },
  { path: "learning tools", description: "Roteamento ACO de ferramentas por intent (pheromone trails intent→tool)" },
  { path: "learning trajectory-recall", description: "Recorda trajetórias similares por sequência de ferramentas (ReasoningBank)" },
  { path: "learning trajectory-record", description: "Registra uma trajetória de execução (tool_sequence) para recall futuro (ReasoningBank)" },
  { path: "lifecycle", description: "Fan out analyze() modes for a lifecycle phase (ANALYZE/DESIGN/PLAN/IMPLEMENT/VALIDATE/REVIEW/HANDOFF/DEPLOY/LISTENING) into one report" },
  { path: "lint", description: "Run eslint on affected files (graph-aware) or entire project" },
  { path: "lint-files", description: "Check source files for 800-line compliance; exit 1 if violations found" },
  { path: "login", description: "Autentica no GitHub Copilot (device-flow ou --token) p/ o provider HTTP direto" },
  { path: "logout", description: "Remove o token salvo do GitHub Copilot" },
  { path: "loop", description: "Run an inner agf command on an interval, or drive a goal-rubric loop until it passes" },
  { path: "loop list", description: "List all loop jobs from the registry" },
  { path: "loop names", description: "List all saved named loop definitions" },
  { path: "loop run", description: "Run a previously saved named loop" },
  { path: "loop save", description: "Save a named reusable loop definition" },
  { path: "loop start", description: "Start a background loop job (detached, non-blocking)" },
  { path: "loop status", description: "Show a single loop job by id" },
  { path: "loop stop", description: "Stop a loop job by id, or \"all\" to stop every running loop" },
  { path: "lsp", description: "Language server bridge: status of configured servers" },
  { path: "lsp apply-edit", description: "Apply an LSP workspace edit (JSON) to disk" },
  { path: "lsp find-symbol", description: "Find a symbol by name path (e.g. \"ClassName/methodName\") in a precomputed document-symbol tree" },
  { path: "lsp status", description: "List configured language servers and their current status" },
  { path: "marketplace", description: "Manage the agf skill/plugin marketplace" },
  { path: "marketplace add", description: "Add a git source and index its items" },
  { path: "marketplace list", description: "List registered sources and available items" },
  { path: "mcp", description: "Remote MCP client inspection (transport/auth state, no network calls)" },
  { path: "mcp inspect", description: "Inspect the transport and auth state agf would use for a remote MCP server (no network calls)" },
  { path: "mcp probe", description: "Attempt to connect to a configured MCP server and report reachability (makes a real network/spawn call)" },
  { path: "mcp tool-context", description: "Resolve whether MCP tool definitions load directly or defer to search, based on --threshold (no network calls)" },
  { path: "memory", description: "Gerencia memórias do projeto (write/read/list/search/rm)" },
  { path: "memory helper", description: "Registro de helpers reutilizáveis (memories/helpers/<key>)" },
  { path: "memory helper get", description: "Descobre um helper previamente persistido por chave" },
  { path: "memory helper persist", description: "Persiste um fragmento de helper sob uma chave estável (idempotente)" },
  { path: "memory list", description: "Lista as memórias do projeto" },
  { path: "memory mine-conversation", description: "Extrai fatos memoráveis (Decision/Error/Fix/Lesson/Warning/Gotcha) de um log JSONL de sessão" },
  { path: "memory pack", description: "Monta o pack de memória top-N por salience sob um teto de tokens (node_2a8c83993c72)" },
  { path: "memory prefetch", description: "Busca memórias via MemoryManager (builtin + honcho opcional) e retorna um bloco fenced pronto para prompt" },
  { path: "memory read", description: "Lê uma memória" },
  { path: "memory rm", description: "Remove uma memória" },
  { path: "memory search", description: "Busca memórias por conteúdo textual" },
  { path: "memory write", description: "Escreve uma memória (conteúdo inline ou de arquivo)" },
  { path: "metrics", description: "Métricas de token do loop autônomo (tokens/task, tokens/sessão) a partir do llm_call_ledger" },
  { path: "migrate-ac", description: "Fold legacy acceptance_criteria child nodes into parent task.ac[] (dry-run by default)" },
  { path: "model", description: "Seleciona/inspeciona o modelo do tier-router; 'auto' roteia por tarefa" },
  { path: "model current", description: "Mostra o modelo/modo selecionado" },
  { path: "model features", description: "Extrai e persiste o vetor de features RL (taskType/acCount/blastRadius/hasExternalDeps) de uma task" },
  { path: "model list", description: "Lista o pool agrupado por tier" },
  { path: "model route", description: "Mostra qual modelo o router escolhe para um tipo de tarefa ou tier" },
  { path: "model set", description: "Fixa um modelo (id do pool) ou 'auto' para roteamento por tarefa" },
  { path: "montar-output", description: "RAG-OUT: recupera o scaffold adequado (preenche slots) ou gera, por objetivo" },
  { path: "mrd", description: "Detect merge/review/deprecate candidates in the graph (from existing graph data, zero token)" },
  { path: "next", description: "Puxa a próxima task desbloqueada (pull system, WIP=1) — fase BUILD" },
  { path: "node", description: "CRUD e mutações de nós (add/show/update/status/move/clone/rm) — zero MCP" },
  { path: "node add", description: "Cria um novo nó no grafo" },
  { path: "node clone", description: "Clona um nó (status resetado p/ backlog)" },
  { path: "node move", description: "Reparenta um nó (atualiza parentId + aresta parent_of)" },
  { path: "node promote", description: "Sugere ou executa promoção de épico (checkEpicPromotion/autoPromoteEpic/cascadeDownOnDone)" },
  { path: "node rationale", description: "ADR-lite: lê/escreve o rationale de decisão de um nó (metadata + description)" },
  { path: "node rationale get", description: "Lê o rationale de decisão armazenado no nó" },
  { path: "node rationale set", description: "Grava o rationale de decisão (decision/why/alternatives/consequences) no nó" },
  { path: "node replace", description: "Recria um nó preservando suas arestas (rewired para o novo ID) — evita orfanizar edges de node rm + node add" },
  { path: "node restore", description: "Restaura um nó arquivado de volta ao grafo" },
  { path: "node rm", description: "Remove um nó do grafo (soft-delete — use restore para reverter)" },
  { path: "node show", description: "Mostra um nó e suas arestas" },
  { path: "node status", description: "Define o status de um nó (com validação status_flow)" },
  { path: "node update", description: "Atualiza campos de um nó (exceto status — use `node status`)" },
  { path: "okr", description: "OKR cockpit — one line per epic: objective, KR attainment and derived status" },
  { path: "okr set", description: "Declara o KR de um épico (target/current/unit) em metadata.kr" },
  { path: "out-of-scope", description: "Decisões de escopo explicitamente descartadas (.out-of-scope/*.md) — evita re-litigar a mesma ideia" },
  { path: "out-of-scope check", description: "Verifica se um conceito já foi descartado antes (similaridade de tokens)" },
  { path: "out-of-scope list", description: "Lista todas as decisões de fora-de-escopo registradas" },
  { path: "out-of-scope record", description: "Registra um conceito como fora de escopo, com a razão" },
  { path: "parse-api", description: "Parseia uma spec OpenAPI 2.0/3.0 (YAML/JSON) ou WSDL em endpoints + schemas estruturados" },
  { path: "permissions", description: "ACL de projeto (allow/deny/ask) por ação/recurso — PermissionStore" },
  { path: "permissions check", description: "Verifica se existe uma regra para ação/recurso" },
  { path: "permissions delete", description: "Remove uma regra de permissão" },
  { path: "permissions list", description: "Lista as regras de permissão de um projeto" },
  { path: "permissions set", description: "Define (ou atualiza) uma regra de permissão" },
  { path: "phase", description: "Mostra a taxonomia de fases (3 canônicas ← 9 internas) e detecta a fase atual do grafo" },
  { path: "pipeline", description: "Compound commands: multiple operations in a single store cycle (faster)" },
  { path: "pipeline next-context", description: "Find next task + load its context (1 store open)" },
  { path: "pipeline next-context-start", description: "Alias for next-start: find + context + mark in_progress" },
  { path: "pipeline next-start", description: "Find next task + load context + mark in_progress (1 store open)" },
  { path: "plugin", description: "Manage plugins (install, remove, enable, disable, list, info)" },
  { path: "prediction-feedback", description: "Loop de correção de previsões erradas — busca por erros passados antes de repeti-los" },
  { path: "prediction-feedback list", description: "Lista todos os registros de correção" },
  { path: "prediction-feedback record", description: "Registra uma previsão errada e sua correção" },
  { path: "prediction-feedback search", description: "Busca correções passadas por substring (query/correction)" },
  { path: "preflight", description: "Golden-rule guard: git-history + graph dedupe before implementing (zero MCP, ~0 token)" },
  { path: "preset", description: "Manage workflow presets (list, apply, show)" },
  { path: "principles", description: "O credo de engenharia da CLI: Clean Code · XP · TDD · Lean + λ_flow (economia de token)" },
  { path: "principles list", description: "Lista os princípios agrupados por categoria" },
  { path: "principles show", description: "Detalha um princípio (título, categoria, statement, rationale)" },
  { path: "profile", description: "Bundles de trabalho: tier de modelo + flow + retries" },
  { path: "profile list", description: "Lista os profiles disponíveis" },
  { path: "profile show", description: "Detalha um profile" },
  { path: "provenance", description: "Escada epistêmica (claim→cited→validated→proven): promote/downgrade/hash — gates de honestidade, local" },
  { path: "provenance downgrade", description: "Reverte o tier de um node quando a evidência cai (forget-gate)" },
  { path: "provenance hash", description: "Recibo determinístico local (sha256 canônico) — habilita o tier proven sem rede" },
  { path: "provenance mix", description: "Distribuição de tiers + flag de baixa maturidade sobre um conjunto de nodes (JSON)" },
  { path: "provenance promote", description: "Valida a evidência exigida para promover um node a um tier" },
  { path: "provenance source-supersede", description: "Registra uma fonte corrigida com edge supersedes para a fonte anterior" },
  { path: "provenance source-write", description: "Escreve uma fonte imutável (write-once); reescrita com conteúdo diferente falha" },
  { path: "provider", description: "Provider de modelo (Copilot default; OpenAI-compatible; exclui Anthropic)" },
  { path: "provider current", description: "Mostra o provider ativo (resolvido com o ambiente + setting)" },
  { path: "provider failover", description: "Define a cadeia de failover (ex.: \"openrouter,ollama:qwen2.5-coder:7b\"); sem arg mostra; --clear limpa" },
  { path: "provider list", description: "Lista os providers disponíveis" },
  { path: "provider set-url", description: "Define/limpa o endpoint do provider ativo (sem url = limpa → volta ao padrão)" },
  { path: "provider use", description: "Define o provider ativo do projeto (opcional: --base-url p/ servidor local/remoto)" },
  { path: "quality", description: "Gate de qualidade 95/95 (testes + logs) sobre src/ — falha (exit≠0) se abaixo do limiar" },
  { path: "quality-policy", description: "Políticas declarativas de qualidade — gates block/warn sobre métricas nomeadas (Lamport 1977)" },
  { path: "quality-policy activate", description: "Ativa uma política (desativa as demais)" },
  { path: "quality-policy create", description: "Cria uma política (inativa por padrão)" },
  { path: "quality-policy evaluate", description: "Avalia uma política (ou a ativa) contra métricas fornecidas" },
  { path: "quality-policy show", description: "Mostra uma política por ID, ou a ativa se omitido" },
  { path: "query", description: "Consulta nós por tipo/status/parent/texto (query_graph/list)" },
  { path: "question", description: "Human-in-the-loop question lifecycle (ask → reply/reject → list) via HumanGateService" },
  { path: "question ask", description: "Ask a question, optionally reply or reject it in the same call, and return the full lifecycle" },
  { path: "recent", description: "Lista pastas de projeto recentemente usadas (histórico de StoreManager.swap)" },
  { path: "reclassify-structural", description: "Reclassifica nodes com título estrutural (TIER X, Roadmap, Sequenciamento...) como implementable=false" },
  { path: "reference", description: "Print the compiled agf reference guide (tools, skills, phases, gates)" },
  { path: "replan-analyze", description: "Analisa saúde do sprint (cycle-time divergence, parent-blocking) e propõe replanejamento" },
  { path: "retrieve", description: "Retrieve a cached original by ⟨ccr:hash⟩ or a tool-output://<hash> handle — optionally BM25-ranked by --query" },
  { path: "retrieve-command", description: "RAG-IN: recupera o comando exato para uma intenção (fallback --help sob o limiar)" },
  { path: "risk", description: "Risk management: triage open risks (promote/accept/close)" },
  { path: "risk triage", description: "Triage open risk nodes (dry-run by default)" },
  { path: "role", description: "Register or inspect which agent role (implementor/reviewer/validator) is assigned to a task" },
  { path: "role get", description: "Get the registered agent role for a task" },
  { path: "role set", description: "Register an agent role for a task" },
  { path: "rules-filter", description: "Filter a rule-pack catalogue JSON to the active language stack (src/core/config/language-rules-filter.ts)" },
  { path: "run", description: "Execução one-shot: implementa um prompt ad-hoc (gera → aplica → testa) via SDK do Copilot" },
  { path: "sandbox", description: "Wave-12 sandbox: stack detection (npm/maven/gradle/go/pip) and process-isolated builds" },
  { path: "sandbox architecture", description: "Print the Wave-12 sandbox functional architecture document (5 layers, key constraints)" },
  { path: "sandbox build", description: "Run a build/test command under process isolation, capturing stdout/stderr with a hard timeout" },
  { path: "sandbox detect", description: "Detect the build/test stack (npm/maven/gradle/go/pip) via marker files, no subprocess spawn" },
  { path: "sandbox resolve-isolation", description: "Probe docker/podman/process availability and resolve the isolation mode `agf sandbox build` would fall back to" },
  { path: "sandbox-gate", description: "Utilitários de sandbox fs/network (PermissionsGate) — `sandbox-gate check <command>`" },
  { path: "sandbox-gate check", description: "Evaluate a shell command against a filesystem/network sandbox policy" },
  { path: "savings", description: "Tabela cumulativa de economia de tokens (tok_in, tok_out, tok_cache, cost)" },
  { path: "scaffold", description: "Geração determinística de scaffold/boilerplate (acoplador determinístico, async via hooks)" },
  { path: "scan", description: "Aggregate quality findings from harness, typecheck, security, and taint sources" },
  { path: "scan-binaries", description: "Write SCANINFO.json (release trust: sha256+signature+VirusTotal verdict) next to BUILDINFO" },
  { path: "scan-binaries check-served", description: "Verify the sha256 each release asset serves over HTTPS matches BUILDINFO (catches a stale CDN edge)" },
  { path: "scan-repos", description: "Explora repos vizinhos: fingerprint determinístico + diff de capacidades vs agf → insights ranqueados" },
  { path: "scan-silent-failures", description: "Scan a directory for masking fallbacks (|| [], || '', empty catch, @ts-expect-error)" },
  { path: "scenario", description: "Roda a suíte de self-check ScenarioRunner (mutation/property testing, DB real em memória)" },
  { path: "scenario browser", description: "Roda um cenário de browser e grava o veredito do oráculo para uma task de superfície" },
  { path: "search", description: "Busca FTS5/BM25 sobre os nós do grafo (tool MCP `search`)" },
  { path: "sentrux", description: "Sentrux MCP tool bridge: scan, session lifecycle, quality gates (requires a live Sentrux MCP server)" },
  { path: "sentrux check-rules", description: "List active Sentrux rule violations" },
  { path: "sentrux dsm", description: "Fetch the Sentrux dependency structure matrix" },
  { path: "sentrux evolution", description: "Fetch Sentrux quality-trend snapshots" },
  { path: "sentrux health", description: "Check Sentrux server health" },
  { path: "sentrux rescan", description: "Re-run the last Sentrux scan" },
  { path: "sentrux scan", description: "Run a Sentrux quality scan" },
  { path: "sentrux session-end", description: "End a Sentrux quality session and report the issue delta" },
  { path: "sentrux session-start", description: "Start a Sentrux quality session" },
  { path: "sentrux test-gaps", description: "Fetch Sentrux test-coverage gaps" },
  { path: "sequence", description: "Auto-sequence a parent's children into a depends_on chain, ordered by createdAt (WIP=1 enforcement)" },
  { path: "session", description: "Inspect the unified session/runtime read-model (show, grants, events)" },
  { path: "session compact", description: "Gzip-compress rollout JSONL files older than --max-age-days (cold-storage compaction)" },
  { path: "session config", description: "Show the harness-level session config (preset, provider, model pin, flags)" },
  { path: "session dispatch", description: "Send a command DOWN into the session loop and capture the upward events" },
  { path: "session events", description: "List the upward session events — persisted history + the channels (or stream with --follow)" },
  { path: "session grants", description: "Show the grant verdict + approval status per capability" },
  { path: "session show", description: "Assemble and print the unified session read-model" },
  { path: "session subagents", description: "List the subagents the harness tracks (live swarm registry)" },
  { path: "session write", description: "Append a message to the active (or newly created) live thread — the session write path" },
  { path: "skill", description: "Lista e exibe skills (instruções para agentes)" },
  { path: "skill create", description: "Cria uma custom skill persistida no grafo (project-scoped, SQLite)" },
  { path: "skill disable", description: "Desativa uma skill para o projeto atual" },
  { path: "skill discover", description: "3-tier skill discovery para uma página (workspace + domain skills persistidas + sinais de interação do HTML)" },
  { path: "skill enable", description: "Ativa uma skill para o projeto atual" },
  { path: "skill install", description: "Instala uma skill de um repositório git no diretório de skills da sua CLI" },
  { path: "skill list", description: "Lista as skills disponíveis (src/skills, .agents/skills, .claude/skills)" },
  { path: "skill new", description: "Scaffold um SKILL.md numa raiz que o `skill list` varre (--dir = raiz; --dest p/ caminho explícito)" },
  { path: "skill propose", description: "Gera um draft de skill a partir da trajetória de uma task concluída (nunca publica direto)" },
  { path: "skill show", description: "Imprime as instruções completas de uma skill" },
  { path: "snapshot", description: "Cria/lista/restaura snapshots do grafo (create/list/restore)" },
  { path: "snapshot create", description: "Cria um snapshot do grafo atual" },
  { path: "snapshot list", description: "Lista snapshots existentes" },
  { path: "snapshot restore", description: "Restaura um snapshot" },
  { path: "spec", description: "Spec generation and validation (generate, validate, list-templates)" },
  { path: "spec-sync", description: "Specs vivos: register/list/status/link (versionados)" },
  { path: "spec-sync link", description: "Liga um spec a um node do grafo (implements)" },
  { path: "spec-sync list", description: "Lista os specs do projeto" },
  { path: "spec-sync register", description: "Registra um spec versionado a partir de um arquivo" },
  { path: "spec-sync status", description: "Compara o conteúdo atual do arquivo com o spec registrado" },
  { path: "spec-triage", description: "Triage orphan spec-nodes (requirement/interface/contract without implementers)" },
  { path: "spec-triage close-satisfied", description: "Satisfy backlog spec-nodes whose parent/implementers are already done (backfill close-on-done)" },
  { path: "spec-triage triage", description: "Triage orphan spec-nodes (requirement/interface/contract without implementers)" },
  { path: "start", description: "Start next task: wake-up + next + context + mark in_progress" },
  { path: "stats", description: "Mostra contagens do grafo persistente (nodes/edges por tipo e status)" },
  { path: "status", description: "Painel: provider/modelo/cache + tokens/$ + economia (visão única)" },
  { path: "submit", description: "Modo delegado: ingere o resultado do executor (brief) → valida → blast → DoD → done" },
  { path: "swarm", description: "Coordenação multi-agente sobre o grafo (sessão/claim/mailbox/consensus) — opt-in, não toca no loop" },
  { path: "swarm ack", description: "Confirma uma mensagem (→acked)" },
  { path: "swarm agents", description: "Lê status ao vivo dos agentes (heartbeat + locks + task atual)" },
  { path: "swarm batch", description: "Puxa o conjunto independente em até k claims paralelos (WIP relaxado só no set independente)" },
  { path: "swarm bench", description: "Mede wall-clock serial vs. batch sobre o MESMO conjunto reivindicado (prova sobreposição real)" },
  { path: "swarm claim", description: "Reivindica um recurso (lease+TTL) — exclusão mútua entre agentes" },
  { path: "swarm consensus", description: "Consolida votos por maioria simples (floor(N/2)+1)" },
  { path: "swarm fan-out", description: "Builds delegated briefs for N nodes concurrently, optionally bounded by a token ceiling" },
  { path: "swarm init", description: "Cria uma sessão de swarm (pending)" },
  { path: "swarm recv", description: "Recebe a mensagem pendente mais antiga (→delivered)" },
  { path: "swarm release", description: "Libera um lease (idempotente)" },
  { path: "swarm scale", description: "Ajusta o teto de agentes (1..32)" },
  { path: "swarm send", description: "Envia mensagem agente-a-agente (courier)" },
  { path: "swarm start", description: "Ativa uma sessão de swarm" },
  { path: "swarm status", description: "Lê uma sessão de swarm" },
  { path: "swarm stop", description: "Para uma sessão de swarm" },
  { path: "swarm sweep", description: "Sweep expired claim leases so tasks become pullable again" },
  { path: "tdd-score", description: "Compute TDD quality score (0–100) for a task based on coverage, assertion diversity, and test density" },
  { path: "template", description: "Templates de decomposição reutilizáveis (list, apply)" },
  { path: "template apply", description: "Instancia um template em nodes+edges (--var k=v, --parent <id>)" },
  { path: "template list", description: "Lista os templates registrados no grafo" },
  { path: "template registry", description: "Templates de task persistidos (SQLite, project-scoped) — reuso entre decomposições" },
  { path: "template registry get", description: "Busca um template persistido pelo nome" },
  { path: "template registry list", description: "Lista os templates persistidos do projeto ativo" },
  { path: "template registry rm", description: "Remove um template persistido pelo nome" },
  { path: "template registry save", description: "Persiste um novo template de task reutilizável (subtasks via JSON)" },
  { path: "test", description: "Run vitest tests, graph-aware: default runs affected tests for current task" },
  { path: "trace", description: "Traces de execução persistentes — spans, custo e latência (Observability Theorem, Kalman 1960)" },
  { path: "trace begin", description: "Inicia um trace" },
  { path: "trace by-node", description: "Lista os traces de um node" },
  { path: "trace cost", description: "Custo agregado por node, ou resumo geral se omitido" },
  { path: "trace end", description: "Encerra um trace (status: completed|error)" },
  { path: "trace record-result", description: "Persiste o resultado de uma tool call sob um trace (ToolResultStore, audit/replay)" },
  { path: "trace results", description: "Lista os resultados de tool persistidos sob um trace" },
  { path: "trace results-by-tool", description: "Lista os resultados mais recentes de uma tool, no projeto atual" },
  { path: "trace show", description: "Mostra um trace + seus spans" },
  { path: "tui", description: "Abre a TUI interativa (dashboard do grafo + tokens)" },
  { path: "ubiquitous-language", description: "Vocabulário canonical do domínio — seção \"## Vocabulário Canonical\" em CONTEXT.md" },
  { path: "ubiquitous-language add", description: "Adiciona (ou completa) um termo no vocabulário canonical" },
  { path: "ubiquitous-language list", description: "Lista os termos já registrados" },
  { path: "ui", description: "Web mínima de progresso (grafo + tokens + logs ao vivo) numa porta custom" },
  { path: "upgrade", description: "Self-update the standalone binary to the latest published version" },
  { path: "usage", description: "Command usage analytics: track frequency, report trends, auto-generate wrappers" },
  { path: "usage report", description: "Show most-used commands and suggest missing wrappers" },
  { path: "usage wrap", description: "Auto-generate an agf wrapper for a native command" },
  { path: "validate", description: "Report-only validator checks (ac/dor/dod/integrity/flow), dispatched by --action" },
  { path: "verify-ac", description: "Check whether a node's AC is already satisfied by existing code before implementing from scratch" },
  { path: "wave12-5w2h", description: "Print the Wave-12 Sandbox Build 5W2H strategic planning document" },
  { path: "web-parity", description: "Deterministic gap report — CLI capabilities without a corresponding web dashboard view" },
  { path: "web-search", description: "Busca externa via Exa/Tavily (ExternalSearchPort), deduped + RRF-ranked" },
  { path: "welcome", description: "Zero-token orientation: stats + next task + lifecycle skills" },
  { path: "wire-check", description: "Signal mock-gated branches (useMock=false, !mock) never activated by any real (non-test) caller" },
  { path: "wire-dormant", description: "Lista capacidades dormentes e injeta WIRE-tasks no backlog (dry-run por default)" },
  { path: "workspace", description: "Workspace state lifecycle (snapshot/track/restore/revert/diff) via WorkspaceStateService" },
  { path: "workspace diff", description: "Create two snapshots (fromLabel, toLabel) and diff them" },
  { path: "workspace snapshot", description: "Track files, create a snapshot, and optionally restore or revert it in the same call" },
]
